# Generated by Django 4.1.11 on 2023-09-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(help_text='Created date')),
                ('updated_at', models.DateTimeField(help_text='Updated date')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('favourite_count', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(help_text='Created date')),
                ('updated_at', models.DateTimeField(help_text='Updated date')),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=128)),
                ('password', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
