# Generated by Django 4.1.11 on 2023-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated date')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('fullname', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated date')),
                ('title', models.CharField(max_length=250, null=True)),
                ('body', models.TextField(help_text='Article description', null=True)),
                ('favourite_count', models.PositiveBigIntegerField(default=0, help_text='Number of favorite of an article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
