version: '3'

services:
  web:
    build: .
    command: >
      bash -c "cd newsmanagement && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    container_name: newsmanagement
    network_mode: "host"
